### ISSUE TITLE
enable filter in configuration

### ISSUE THREAD

**Issue by romankonz** [doctrine/DoctrineMongoODMModule#147]
it is not possible to enable a filter by configuration.
It's possible in the Symfony Bundle: http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html

This would be bery useful!

**Comment by gianarb** [comment]
Hi @romankonz in this moment I'm not code about this feature but I see this chapter into the configuration

https://github.com/doctrine/DoctrineMongoODMModule/blob/e4b77226f09c21ebf01021f223f3e113430156f4/config/module.doctrine-mongo-odm.local.php.dist#L33

**Comment by romankonz** [comment]
yes, it is possible to attach a filter, but it is disabled by default.
In the symfony you can enable it with a parameter

like
``` 
filters:
    filter-name:
        class: Class\Example\Filter\ODM\ExampleFilter
        enabled: true // this is not possible with the odm module
```
