### ISSUE TITLE
Unable to make it work under docker with docker-compose.yml

### ISSUE THREAD

**Issue by mdjaman** [doctrine/DoctrineMongoODMModule#203]
Could not make it run under docker with docker-compose 
```
doctrine' => array(
        'connection' => array(
            'odm_default' => array(
                /*'connectionString' => sprintf('mongodb://%s:%d/%s',
                    getenv('MONGODB_HOST'),
                    getenv('MONGODB_PORT'),
                    getenv('MONGODB_DATABASE')
                ),*/
                'server' => getenv('MONGODB_HOST'),
                'port' => getenv('MONGODB_PORT'),
                'dbname' => getenv('MONGODB_DATABASE'),
            ),
        ),
       ....
),
```
And my .env file

```
MONGODB_HOST=mongodb
MONGODB_PORT=27037
MONGODB_DATABASE=ems
MONGODB_USERNAME=
MONGODB_PASSWORD=
MONGODB_AUTH_MECHANISM="MONGODB-CR"
MONGODB_DRIVER=mongodb
```
And finally docker-compose.yml file

```
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ems-web
    ports:
     - "8100:80"
    environment:
      PHP_XDEBUG_ENABLED: 1
    volumes:
     - .:/var/www
    #restart: always
    links:
     - mongodb
    networks:
     - development_network
  mongodb:
    image: mongo
    container_name: ems-mongodb
    volumes:
      - ./docker/mongo/db:/var/lib/mongo
      #- ./data/initdb/mongo:/docker-entrypoint-initdb.d
    #restart: always
    ports:
     - "27037:27017"
#    env_file: .env
#    environment:
#      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
#      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    command: ["mongod"]
    networks:
     - development_network
networks:
  development_network:
```
